const fs = require('fs');
const path = require('path');
const assert = require('assert');
const root = path.resolve(__dirname,'..');
const sec = fs.readFileSync(path.join(root,'V12_SecuritySync.gs'),'utf8');
const index = fs.readFileSync(path.join(root,'Index.html'),'utf8');
const rpc = fs.readFileSync(path.join(root,'V12_RpcGateway.gs'),'utf8');
assert(sec.includes("const SGO_APP_VERSION_V1215 = '12.18.3'"),'server version not v12.18.3');
assert(index.includes('>v12.18.3</span>'),'client badge not v12.18.3');
assert(sec.includes('buildLoginCoreStateV12152_(spreadsheet, user, legacyState, collaborators)'),'authentication does not reuse preloaded collaborators');
assert(sec.includes('function buildLoginCoreStateV12152_(spreadsheet, user, legacyConfig, preloadedCollaborators)'),'core state does not accept preloaded collaborators');
assert(sec.includes('Array.isArray(preloadedCollaborators)'),'preloaded collaborators are not used');
const authStart=sec.indexOf('function authenticateSessionServer');
const authEnd=sec.indexOf('\nfunction createSessionV12_',authStart);
const auth=sec.slice(authStart,authEnd);
assert(!auth.includes('buildScopedStateV12_('),'login still builds full scoped state');
assert(auth.includes('needsCredentialMigration'),'credential migration was not deferred');
assert(index.includes('v12152StartPostLoginLoads'),'client post-login loader missing');
assert(rpc.includes("case 'loadDeferredBootstrapServer': return loadDeferredBootstrapServer(payload);"),'deferred bootstrap RPC missing');
assert(rpc.includes("case 'migrateMyCredentialAfterLoginServer': return migrateMyCredentialAfterLoginServer(payload);"),'deferred credential RPC missing');
console.log('V12_15_2_PERFORMANCE_TESTS_OK',JSON.stringify({tests:10}));
